export const ORDER_CREATE_REQUEST="ORDER_CREATE_REQUEST"
export const ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS"
export const ORDER_CREATE_FAIL="ORDER_CREATE_FAIL"

export const ORDER_DETAIL_REQUEST="ORDER_DETAIL_REQUEST"
export const ORDER_DETAIL_SUCCESS="ORDER_DETAIL_SUCCESS"
export const ORDER_DETAIL_FAIL="ORDER_DETAIL_FAIL"

export const ORDER_LISTS_REQUEST="ORDER_LISTS_REQUEST"
export const ORDER_LISTS_SUCCESS="ORDER_LISTS_SUCCESS"
export const ORDER_LISTS_FAIL="ORDER_LISTS_FAIL"
export const ORDER_LISTS_RESET="ORDER_LISTS_RESET"

export const ORDER_PAY_REQUEST="ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS="ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL="ORDER_PAY_FAIL"
export const ORDER_PAY_RESET="ORDER_PAY_RESET"

export const ORDER_ADMIN_REQUEST="ORDER_ADMIN_REQUEST"
export const ORDER_ADMIN_SUCCESS="ORDER_ADMIN_SUCCESS"
export const ORDER_ADMIN_FAIL="ORDER_ADMIN_FAIL"

export const ORDER_DELIVER_REQUEST="ORDER_DELIVER_REQUEST"
export const ORDER_DELIVER_SUCCESS="ORDER_DELIVER_SUCCESS"
export const ORDER_DELIVER_FAIL="ORDER_DELIVER_FAIL"
export const ORDER_DELIVER_RESET="ORDER_DELIVER_RESET"

